import { describe, expect, it } from 'vitest';
import { bindHwidV2, validateHwidV2, resetHwidV2, setHwidStatusV2 } from '../src/security/hwid-v2.js';

function makeDb() {
  const state = { licenses: [{ id: 'l1', user_id: null, key_owner_id: 'u1', status: 'active', expires_at: null }], bindings: [] };
  const prepare = (sql) => ({ bind: (...args) => ({ first: async () => { if (sql.includes('FROM licenses')) return state.licenses.find((x) => x.id === args[0]) ?? null; if (sql.includes('FROM hwid_bindings_v2') && sql.includes("status = 'blocked'") && sql.includes('owner_id = ?1')) return state.bindings.find((x) => x.owner_id === args[0] && x.hwid_hash === args[1] && x.status === 'blocked') ?? null; if (sql.includes('FROM hwid_bindings_v2') && sql.includes('license_id = ?1') && sql.includes('hwid_hash = ?2')) return state.bindings.find((x) => x.license_id === args[0] && x.hwid_hash === args[1]) ?? null; if (sql.includes('COUNT(*)')) return { total: state.bindings.filter((x) => x.license_id === args[0] && x.status === 'active').length }; if (sql.includes('SELECT id FROM hwid_bindings_v2')) return state.bindings.find((x) => x.id === args[0] && x.owner_id === args[1]) ?? null; return null; }, all: async () => ({ results: state.bindings }), run: async () => { if (sql.startsWith('INSERT INTO hwid_bindings_v2')) state.bindings.push({ id: args[0], owner_id: args[1], license_id: args[2], hwid_hash: args[3], status: 'active' }); if (sql.startsWith('UPDATE hwid_bindings_v2 SET status')) { const row = state.bindings.find((x) => x.id === args[3] && x.owner_id === args[4]); if (row) row.status = args[0]; } if (sql.startsWith('DELETE FROM hwid_bindings_v2')) state.bindings = state.bindings.filter((x) => !(x.owner_id === args[0] && x.license_id === args[1] && x.status === 'active')); return { meta: { changes: 1 } }; } }) });
  return { state, prepare };
}
function dbEnv(db) { return { DB: db }; }
const hash = async (value) => { const d = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value)); return [...new Uint8Array(d)].map((b) => b.toString(16).padStart(2, '0')).join(''); };

describe('Phase 16 HWID compatibility', () => {
  it('binds a device and stores only a hash', async () => { const db = makeDb(); const result = await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-secret-1' }); expect(result.ok).toBe(true); expect(result.existing).toBe(false); expect(result.fingerprint).toBe((await hash('device-secret-1')).slice(0, 12)); });
  it('rejects a third active device when max_devices is reached', async () => { const db = makeDb(); await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-1' }); const result = await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-2' }); expect(result.ok).toBe(false); expect(result.reason).toBe('DEVICE_LIMIT_REACHED'); });
  it('validates matching HWID and denies mismatch', async () => { const db = makeDb(); await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-1' }); const valid = await validateHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-1' }); expect(valid.ok).toBe(true); const invalid = await validateHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'wrong-device' }); expect(invalid.ok).toBe(false); expect(invalid.reason).toBe('HWID_MISMATCH'); });
  it('blocks and unblocks a device', async () => { const db = makeDb(); const first = await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-1' }); const blocked = await setHwidStatusV2(dbEnv(db), { ownerId: 'u1', deviceId: first.deviceId, status: 'blocked' }); expect(blocked.ok).toBe(true); const unblocked = await setHwidStatusV2(dbEnv(db), { ownerId: 'u1', deviceId: first.deviceId, status: 'active' }); expect(unblocked.ok).toBe(true); });
  it('resets active bindings for the owner license', async () => { const db = makeDb(); await bindHwidV2(dbEnv(db), { licenseId: 'l1', ownerId: 'u1', rawHwid: 'device-1' }); const result = await resetHwidV2(dbEnv(db), { ownerId: 'u1', licenseId: 'l1' }); expect(result.ok).toBe(true); });
});
