name = "frezen"
main = "src/entry-ui.js"
compatibility_date = "2026-08-09"
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"

[vars]
FREZEN_ENV = "development"

[env.staging]
name = "frezen-control-system-v3-staging"
workers_dev = true
vars = { FREZEN_ENV = "staging" }

[env.production]
name = "frezen"
workers_dev = true
vars = { FREZEN_ENV = "production" }

[[env.production.d1_databases]]
binding = "DB"
database_name = "frezen-production"
database_id = "ff6e12e2-c59b-4891-812c-9ce0bbae64fc"

[env.production.triggers]
crons = ["*/15 * * * *"]

# Recommended deployment commands:
# npx wrangler deploy --env staging
# npx wrangler deploy --env production
